Experiment 1: TensorFlow Installation & Version Check

In [24]:
pip install tensorflow

In [12]:
import tensorflow as tf
print(tf.__version__)

2.19.0


Experiment 2: Creating and Printing Tensors


In [19]:

a=tf.constant(5)
print(a)

v=tf.constant([1,2,3,4])
print(v)

m=tf.constant([[1,2], [3,4]])
print(m)

t3=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(t3)


tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


Experiment 3: Basic Tensor Operations

In [21]:
#Scalar tensors
a = tf.constant(10)
b = tf.constant(5)

print(a+b)
print(a-b)
print(a*b)
print(a/b)


tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float64)


In [22]:
#Vector tensors
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [23]:
#2-D matrix
m1 = tf.constant([[2, 4],
                  [6, 8]])

m2 = tf.constant([[1, 2],
                  [3, 4]])

print(m1+m2)
print(m1-m2)
print(m1*m2)
print(m1/m2)


tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  8]
 [18 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)


Experiment 4: Data Types and Shape of Tensors

In [30]:
#scalar
scalar = tf.constant(5, dtype=tf.int32)

print("Scalar Tensor:", scalar)
print("Data Type:", scalar.dtype)
print("Shape:", scalar.shape)
print("Dimensions:", scalar.ndim)

#vector
vector = tf.constant([1, 2, 3, 4], dtype=tf.float32)

print("\nVector Tensor:", vector)
print("Data Type:", vector.dtype)
print("Shape:", vector.shape)
print("Dimensions:", vector.ndim)

#2D MATRIX
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]], dtype=tf.float64)

print("\n2D Matrix Tensor:\n", matrix)
print("Data Type:", matrix.dtype)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)

Scalar Tensor: tf.Tensor(5, shape=(), dtype=int32)
Data Type: <dtype: 'int32'>
Shape: ()
Dimensions: 0

Vector Tensor: tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
Data Type: <dtype: 'float32'>
Shape: (4,)
Dimensions: 1

2D Matrix Tensor:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
Data Type: <dtype: 'float64'>
Shape: (2, 3)
Dimensions: 2


Experiment 5: Converting NumPy Arrays to Tensors

In [31]:
import numpy as np

np_array = np.array([10, 20, 30, 40])
tf_tensor = tf.convert_to_tensor(np_array)

print("NumPy Array:", np_array)
print("TensorFlow Tensor:", tf_tensor)


NumPy Array: [10 20 30 40]
TensorFlow Tensor: tf.Tensor([10 20 30 40], shape=(4,), dtype=int64)
